### ISSUE TITLE
Type exception with OpenCV 4.5.2

### ISSUE THREAD

**Issue by ddonohoe** [colour-science/colour-checker-detection#26]
I moved to a fresh install today, and this happened:

Traceback (most recent call last):
  File "/home/davidd/git/UB-ISP/scripts/color_calib", line 88, in <module>
    result = detect_colour_checkers_segmentation(img, additional_data=True)
  File "/home/davidd/.local/lib/python3.8/site-packages/colour_checker_detection/detection/segmentation.py", line 771, in detect_colour_checkers_segmentation
    for colour_checker in extract_colour_checkers_segmentation(image):
  File "/home/davidd/.local/lib/python3.8/site-packages/colour_checker_detection/detection/segmentation.py", line 694, in extract_colour_checkers_segmentation
    colour_checker = crop_and_level_image_with_rectangle(
  File "/home/davidd/.local/lib/python3.8/site-packages/colour_checker_detection/detection/segmentation.py", line 463, in crop_and_level_image_with_rectangle
    M_r = cv2.getRotationMatrix2D(centroid, angle, 1)
TypeError: Can't parse 'center'. Sequence item with index 0 has a wrong type

Previously cv2 was at version 4.5.1, but with the fresh install it had moved to 4.5.2.

Modifying segmentation.py (line 451) from:
    centroid = as_int_array(contour_centroid(cv2.boxPoints(rectangle)))
to:
    centroid = as_float_array(contour_centroid(cv2.boxPoints(rectangle)))

fixed it for me.

**Comment by KelSolaar** [comment]
Hi @ddonohoe,

Thanks and sorry for the late answer! I have a few things that I will need to squeeze in when I have some spare cycles, this will be included!

Cheers,

Thomas

**Comment by KelSolaar** [comment]
Hi @ddonohoe,

This should be fixed in develop!

Cheers,

Thomas

**Comment by ddonohoe** [comment]
Many thanks Thomas!
