### ISSUE TITLE
Can't parse 'center'. Sequence item with index 0 has a wrong type

### ISSUE THREAD

**Issue by ftn21** [colour-science/colour-checker-detection#34]
i use your code from the examples but i'm getting an error: Can't parse 'center'. Sequence item with index 0 has a wrong type.

here's the code:

```
from colour import read_image
import colour_checker_detection as ccd

path = '/home/ftn21/Documents/ran/colour/img/IMG_1967.png'
image = read_image(path)
arr = ccd.detect_colour_checkers_segmentation(image)
```

here's the console output:

```
runfile('/home/ftn21/Documents/ran/colour/src/exmp_detect.py', wdir='/home/ftn21/Documents/ran/colour/src')
Traceback (most recent call last):

  File "/home/ftn21/Documents/ran/colour/src/exmp_detect.py", line 14, in <module>
    arr = ccd.detect_colour_checkers_segmentation(image)

  File "/home/ftn21/anaconda3/lib/python3.8/site-packages/colour_checker_detection/detection/segmentation.py", line 769, in detect_colour_checkers_segmentation
    for colour_checker in extract_colour_checkers_segmentation(image):

  File "/home/ftn21/anaconda3/lib/python3.8/site-packages/colour_checker_detection/detection/segmentation.py", line 692, in extract_colour_checkers_segmentation
    colour_checker = crop_and_level_image_with_rectangle(

  File "/home/ftn21/anaconda3/lib/python3.8/site-packages/colour_checker_detection/detection/segmentation.py", line 461, in crop_and_level_image_with_rectangle
    M_r = cv2.getRotationMatrix2D(centroid, angle, 1)

TypeError: Can't parse 'center'. Sequence item with index 0 has a wrong type


```

**Comment by KelSolaar** [comment]
Hi @ftn21,

Which version of `colour-checker-detection` and `OpenCV` are you using? Late OpenCV versions have introduced changes that break with the release version of `colour-checker-detection` but should be fixed in the **develop** branch!

Cheers,

Thomas

**Comment by ftn21** [comment]
thank you @KelSolaar,

i am using `colour-checker-detection 0.1.2` and `OpenCV 4.5.3`

**Comment by KelSolaar** [comment]
Yes it is most likely same than #26.

**Comment by ftn21** [comment]
that worked for me, thanks!
